name: Build & Push EmuOS Docker Image

on:
  push:
    branches:
      - main  # Run this on push to main

jobs:
  build:
    name: Build and Push Multi-Arch Docker Image to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed for GHCR push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/tan-tan-san/emuos:latest
